name: CI/CD for Flask Demo

env:
  DB_URL: ${{ secrets.DB_URL }}
  PAT: ${{ secrets.PAT }} # GITHUB_PAT

on:
  push:
    branches:
      - main  # Run workflow on pushes to the main branch
  pull_request:
    branches:
      - main  # Run workflow on pull requests targeting the main branch

jobs:
  # Job 1: Test Python Application
  test-python-app:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.12"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run tests
        env:
          DB_URL: ${{ secrets.DB_URL }}
        run: |
          pytest

  # Job 2: Build Docker Image
  build-docker-image:
    runs-on: ubuntu-latest
    needs: test-python-app  # Run after testing
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.PAT }}  # Use PAT for authentication

      - name: Build Docker image
        run: |
          docker build -t ghcr.io/polumm/flask-demo:latest .

  # Job 3: Push Docker Image
  push-docker-image:
    runs-on: ubuntu-latest
    needs: build-docker-image  # Run after building the image
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.PAT }}  # Use PAT for authentication

      - name: Push Docker image
        run: |
          docker push ghcr.io/polumm/flask-demo:latest
